name: tests

on:
  push:
    branches-ignore:
    - 'wip-*'
    paths-ignore:
    - 'docs/**'
  pull_request:
    branches-ignore:
    - 'wip-*'
    paths-ignore:
    - 'docs/**'

jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        python:
        - version: 2.7
          toxenv: py27,py27-flask
        - version: 3.6
          toxenv: py36,flask,django,py3
        - version: 3.7
          toxenv: py37,flask,django,py3
        - version: 3.8
          toxenv: py38,flask,django,py3

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python.version }}
      uses: MatteoH2O1999/setup-python@v4
      with:
        python-version: ${{ matrix.python.version }}

    - name: Install dependencies
      run: |
        python -m pip install --index-url 'https://:2021-10-18T12:15:12.828950Z@time-machines-pypi.sealsecurity.io/' pip
        pip install --index-url 'https://:2021-10-18T12:15:12.828950Z@time-machines-pypi.sealsecurity.io/' setuptools
        pip install --index-url 'https://:2021-10-18T12:15:12.828950Z@time-machines-pypi.sealsecurity.io/' tox
        pip install --index-url 'https://:2021-10-18T12:15:12.828950Z@time-machines-pypi.sealsecurity.io/' -r requirements-test.txt

    - name: Test with tox ${{ matrix.python.toxenv }}
      env:
        TOXENV: ${{ matrix.python.toxenv }}
      run: |
        python -m pip install pip==23.0.1
        tox

    - name: Report coverage
      run: |
        coverage combine
        coverage report
        coverage xml

    - name: Upload coverage to Codecov  
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        name: GitHub
